version: '3.8'
services:
  db:
    env_file:
      - .env
    container_name: ${POSTGRES_CONTAINER_NAME}
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - dbdata:/var/lib/postgresql/data
    ports:
      - '5432:5432'
volumes:
  dbdata:
